apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service-app
  template:
    metadata:
      labels:
        app: payments-service-app
    spec:
      containers:
        - name: payments-service-app
          image: docker.io/jose0613/payments_service:v1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "payments"
            - name: DB_USER
              value: "postgresuser"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  type: NodePort
  selector:
    app: payments-service-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30004
