apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookings-service-app
  template:
    metadata:
      labels:
        app: bookings-service-app
    spec:
      containers:
        - name: bookings-service-app
          image: docker.io/jose0613/bookings_service:v1.0.1
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "bookings"
            - name: DB_USER
              value: "postgresuser"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: bookings-service
spec:
  type: NodePort
  selector:
    app: bookings-service-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
