apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-app
  template:
    metadata:
      labels:
        app: checkout-app
    spec:
      containers:
        - name: checkout-app
          image: docker.io/jose0613/checkout_service:v1.0.27
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  type: NodePort
  selector:
    app: checkout-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
